### PR TITLE
Actually minify

### PR DESCRIPTION
**Pull request by boomzero**
Obfuscating the code is useless, if a person wants to see the source, they can go on github. And the obfuscated code is too slow, and uses more than 8 times more cpu

### CODE REVIEW

**Comment by boomzero** [comment]
@langningchen

**Comment by langningchen** [comment]
That's true, but somebody doesn't know this is no GitHub even if I have mentioned it.

**Comment by langningchen** [comment]
Some people do not obey the GPL licence.

**Comment by boomzero** [comment]
You should at least minify before obfuscation

**Comment by langningchen** [comment]
However, I will accept your suggestion and merge your PR.

**Comment by boomzero** [comment]
> That's true, but somebody doesn't know this is no GitHub even if I have mentioned it.

Umm, don't you install by going to the github release?

**Comment by langningchen** [comment]
> You should at least minify before obfuscation

The obfuscation operation automatically minify the code.

**Comment by langningchen** [comment]
No, they install it by going to [the webtsite](https://langningchen.github.io/XMOJ-Script).

**Comment by langningchen** [comment]
Let me think it a bit longer.

**Comment by boomzero** [comment]
> Some people do not obey the GPL licence.



> That's true, but somebody doesn't know this is no GitHub even if I have mentioned it.

Well you did link to this repository in the code

**Comment by langningchen** [comment]
> > Some people do not obey the GPL licence.
> 
> > That's true, but somebody doesn't know this is no GitHub even if I have mentioned it.
> 
> Well you did link to this repository in the code

Yes, but many people don't spot that!

**Comment by langningchen** [comment]
Well, I have started to remove the JS compress. If I just merge this pull request, people who use compressed script can't get updated. They'll get 404 or they will never be updated. Thank you for your contribute. I will close this pull request.

**Comment by boomzero** [comment]
thx
~~你不打比赛吗~~

**Pull request closed without merging**
