### PR TITLE
fix #41

### LINKED ISSUE #41: [Bug] live playback will play two seperate streams of audio
@langningchen 
How to reproduce:
1. Go to a live playback page like http://www.xmoj.tech/contest_video.php?cid=6255
2. Play it with this script enabled

### PR DESCRIPTION
**Pull request by boomzero**
fix #41 

麻了...

### CODE REVIEW

**Comment by boomzero** [comment]
@langningchen ~理论上来说我可以自己点merge, 但是我怕弄错~

你能review吗

**Comment by langningchen** [comment]
我试试

**Comment by langningchen** [comment]
@boomzero Err... I can't play it. 😕 
image

**Review by langningchen — CHANGES_REQUESTED** [review]
Can not play the video with IDM enabled.

**Comment by boomzero** [comment]
> @boomzero Err... I can't play it. 😕 image

? I can

**Comment by boomzero** [comment]
What's your Browser

**Comment by boomzero** [comment]
I use firefox

**Comment by boomzero** [comment]
Safari Should also work

**Comment by langningchen** [comment]
@boomzero 
`Microsoft Edge Version 118.0.2055.0 (Official build) canary (64-bit)`

**Comment by langningchen** [comment]
Note: I'll be offline for 10 minutes, because I will go to school to have the programming class.

**Comment by langningchen** [comment]
好了

**Comment by langningchen** [comment]
我再看一看

**Comment by langningchen** [comment]
还是不行

**Comment by boomzero** [comment]
> 还是不行

等一下,我没改

**Comment by langningchen** [comment]
我发现一个东西

**Comment by langningchen** [comment]
原来视频是创建了一个`AliPlayer`，存在变量`player`里面

**Comment by langningchen** [comment]
我们等到`player`加载以后执行`player.dispose()`就可以了

**Comment by langningchen** [comment]
似乎好像好了

**Comment by langningchen** [comment]
你试一试，这样应该就好了 @boomzero  
```js
          else if (location.pathname == "/contest_video.php") {
            let ScriptData = document.querySelector("body > div > div.mt-3 > center > script").innerHTML;
            if (document.getElementById("J_prismPlayer0").innerHTML != "") {
                document.getElementById("J_prismPlayer0").innerHTML = "";
                if (player) {
                    player.dispose();
                }
                eval(ScriptData);
            }
            if (UtilityEnabled("DownloadPlayback")) {
                ScriptData = ScriptData.substring(ScriptData.indexOf("{"));
                ScriptData = ScriptData.substring(0, ScriptData.indexOf("}") + 1);
                ScriptData = ScriptData.replace(/([a-zA-Z0-9]+) ?:/g, "\"$1\":");
                ScriptData = ScriptData.replace(/'/g, "\"");
                let VideoData = JSON.parse(ScriptData);
                let RandomUUID = () => {
                    let t = "0123456789abcdef";
                    let e = [];
                    for (let r = 0; r < 36; r++)
                        e[r] = t.substr(Math.floor(16 * Math.random()), 1);
                    e[14] = "4";
                    e[19] = t.substr(3 & e[19] | 8, 1);
                    e[8] = e[13] = e[18] = e[23] = "-";
                    return e.join("");
                };
                let URLParams = new URLSearchParams({
                    "AccessKeyId": VideoData.accessKeyId,
                    "Action": "GetPlayInfo",
                    "VideoId": VideoData.vid,
                    "Formats": "",
                    "AuthTimeout": 7200,
                    "Rand": RandomUUID(),
                    "SecurityToken": VideoData.securityToken,
                    "StreamType": "video",
                    "Format": "JSON",
                    "Version": "2017-03-21",
                    "SignatureMethod": "HMAC-SHA1",
                    "SignatureVersion": "1.0",
                    "SignatureNonce": RandomUUID(),
                    "PlayerVersion": "2.9.3",
                    "Channel": "HTML5"
                });
                URLParams.sort();
                await fetch("https://vod." + VideoData.region + ".aliyuncs.com/?" +
                    URLParams.toString() +
                    "&Signature=" +
                    encodeURIComponent(CryptoJS.HmacSHA1("GET&%2F&" + encodeURIComponent(URLParams.toString()),
                        VideoData.accessKeySecret + "&").toString(CryptoJS.enc.Base64)))
                    .then((Response) => {
                        return Response.json();
                    })
                    .then((Response) => {
                        let DownloadButton = document.createElement("a");
                        DownloadButton.className = "btn btn-outline-secondary";
                        DownloadButton.innerText = "下载";
                        DownloadButton.href = Response.PlayInfoList.PlayInfo[0].PlayURL;
                        DownloadButton.download = Response.VideoBase.Title;
                        document.querySelector("body > div > div.mt-3 > center").appendChild(DownloadButton);
                    });
            }
        }
```

**Comment by boomzero** [comment]
Please wait, I need to do my homework...

**Comment by langningchen** [comment]
OK,

**Comment by boomzero** [comment]
> 你试一试，这样应该就好了 @boomzero
> 
> ```js
>           else if (location.pathname == "/contest_video.php") {
>             let ScriptData = document.querySelector("body > div > div.mt-3 > center > script").innerHTML;
>             if (document.getElementById("J_prismPlayer0").innerHTML != "") {
>                 document.getElementById("J_prismPlayer0").innerHTML = "";
>                 if (player) {
>                     player.dispose();
>                 }
>                 eval(ScriptData);
>             }
>             if (UtilityEnabled("DownloadPlayback")) {
>                 ScriptData = ScriptData.substring(ScriptData.indexOf("{"));
>                 ScriptData = ScriptData.substring(0, ScriptData.indexOf("}") + 1);
>                 ScriptData = ScriptData.replace(/([a-zA-Z0-9]+) ?:/g, "\"$1\":");
>                 ScriptData = ScriptData.replace(/'/g, "\"");
>                 let VideoData = JSON.parse(ScriptData);
>                 let RandomUUID = () => {
>                     let t = "0123456789abcdef";
>                     let e = [];
>                     for (let r = 0; r < 36; r++)
>                         e[r] = t.substr(Math.floor(16 * Math.random()), 1);
>                     e[14] = "4";
>                     e[19] = t.substr(3 & e[19] | 8, 1);
>                     e[8] = e[13] = e[18] = e[23] = "-";
>                     return e.join("");
>                 };
>                 let URLParams = new URLSearchParams({
>                     "AccessKeyId": VideoData.accessKeyId,
>                     "Action": "GetPlayInfo",
>                     "VideoId": VideoData.vid,
>                     "Formats": "",
>                     "AuthTimeout": 7200,
>                     "Rand": RandomUUID(),
>                     "SecurityToken": VideoData.securityToken,
>                     "StreamType": "video",
>                     "Format": "JSON",
>                     "Version": "2017-03-21",
>                     "SignatureMethod": "HMAC-SHA1",
>                     "SignatureVersion": "1.0",
>                     "SignatureNonce": RandomUUID(),
>                     "PlayerVersion": "2.9.3",
>                     "Channel": "HTML5"
>                 });
>                 URLParams.sort();
>                 await fetch("https://vod." + VideoData.region + ".aliyuncs.com/?" +
>                     URLParams.toString() +
>                     "&Signature=" +
>                     encodeURIComponent(CryptoJS.HmacSHA1("GET&%2F&" + encodeURIComponent(URLParams.toString()),
>                         VideoData.accessKeySecret + "&").toString(CryptoJS.enc.Base64)))
>                     .then((Response) => {
>                         return Response.json();
>                     })
>                     .then((Response) => {
>                         let DownloadButton = document.createElement("a");
>                         DownloadButton.className = "btn btn-outline-secondary";
>                         DownloadButton.innerText = "下载";
>                         DownloadButton.href = Response.PlayInfoList.PlayInfo[0].PlayURL;
>                         DownloadButton.download = Response.VideoBase.Title;
>                         document.querySelector("body > div > div.mt-3 > center").appendChild(DownloadButton);
>                     });
>             }
>         }
> ```

It works

**Comment by boomzero** [comment]
@langningchen

**Comment by langningchen** [comment]
太棒了！

**Pull request closed without merging**
